serverAddr = "{{ .Envs.FRP_WORKER_SERVER_ADDR }}"
serverPort = 7000

auth.method = "token" 
auth.token =  "{{ .Envs.FRP_WORKER_AUTH_TOKEN }}"

[[proxies]]
name = "gpu_worker"
type = "stcp"
secretKey = "{{ .Envs.FRP_WORKER_SECRET_KEY }}"
localIP = "127.0.0.1"
localPort = 8080
